export const GAME_LEVELS = "GAME_LEVELS";
export const GAME_LEVEL_DATA = "GAME_LEVEL_DATA";
export const GAME_START = "GAME_START";
export const GAME_CURRENT_TIME = "GAME_CURRENT_TIME";
export const GAME_NEXT_QUESTION = "GAME_NEXT_QUESTION";
export const GAME_CHECK_ANSWER = "GAME_CHECK_ANSWER";
export const GAME_RESULT = "GAME_RESULT";